
apiVersion: v1
kind: Service
metadata:
  name: object-detection
  namespace: default
spec:
  type: NodePort
  selector:
    app: object-detection
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30036
    # externalIPs:
          # - 168.138.15.28
